@echo off
set PROJECT_ROOT=PATH_TO_APP\production_app
set SSH_KEY=PATH_TO_APP\production_app\deployment\KEYFILE.key
set DEPLOY_USER=ubuntu
set DEPLOY_HOST=129.80.99.95
set PUBLIC_HOST=129.80.99.95
set LETSENCRYPT_EMAIL=

set FRONTEND_SUPABASE_URL=
set FRONTEND_SUPABASE_ANON_KEY=
set FRONTEND_WORKER_API_URL=/api

set REMOTE_RELEASE_UPLOAD_DIR=/home/ubuntu
